"""
LangGraph AgentState definition.

AgentState is the shared data structure passed between all nodes in the
LangGraph StateGraph. Every agent reads from and writes to this state.

Using TypedDict (not Pydantic) as required by LangGraph's state management.
"""

from typing import Annotated, Optional
from typing_extensions import TypedDict
import operator

from app.models.paper import Paper
from app.models.summary import ContradictionReport, PaperSummary
from app.models.evaluation import EvaluationResult


class AgentState(TypedDict):
    """
    Shared state for the NeuroAgent LangGraph workflow.

    Fields marked with Annotated[list, operator.add] support LangGraph's
    fan-out / parallel execution — multiple nodes can append to these lists
    without overwriting each other.
    """

    # ── Input ──────────────────────────────────────────────────────────────────
    query: str
    """The original user research query."""

    session_id: str
    """Unique session identifier (UUID). Created at query entry point."""

    user_id: Optional[str]
    """Optional user ID for Mem0 personalization. None for anonymous sessions."""

    max_papers: int
    """Maximum number of papers to fetch (default from config)."""

    # ── Memory Context ─────────────────────────────────────────────────────────
    mem0_context: str
    """
    User's past research context retrieved from Mem0 at session start.
    Empty string if no prior memory exists or user is anonymous.
    """

    # ── Fetcher Output ─────────────────────────────────────────────────────────
    papers: list[Paper]
    """Raw papers fetched by the Fetcher Agent."""

    # ── Summarizer Output ──────────────────────────────────────────────────────
    summaries: list[PaperSummary]
    """Structured summaries produced by the Summarizer Agent."""

    # ── Parallel Branch Outputs ────────────────────────────────────────────────
    contradiction_report: Optional[ContradictionReport]
    """Conflict analysis from the Contradiction Detector Agent."""

    concepts: list[str]
    """Key concepts extracted by the Concept Extractor Agent."""

    # ── Synthesis Output ───────────────────────────────────────────────────────
    final_synthesis: str
    """
    Final comprehensive answer generated by the Synthesis Agent.
    Includes inline citations and is the primary user-facing output.
    """

    # ── Evaluation Output ──────────────────────────────────────────────────────
    evaluation: Optional[EvaluationResult]
    """RAGAS evaluation result. May be None if evaluation is running in background."""

    # ── Error Tracking ─────────────────────────────────────────────────────────
    errors: Annotated[list[str], operator.add]
    """
    Accumulated error messages from any agent.
    Uses operator.add so parallel branches can both append without conflict.
    """

    # ── Metadata ───────────────────────────────────────────────────────────────
    qdrant_context: list[str]
    """
    Semantically similar chunks retrieved from Qdrant for the synthesis step.
    These are the RAG context chunks that RAGAS evaluates against.
    """


def initial_state(
    query: str,
    session_id: str,
    user_id: Optional[str] = None,
    max_papers: int = 10,
) -> AgentState:
    """
    Factory function for a clean initial AgentState.

    Args:
        query: The user's research query.
        session_id: Unique session UUID.
        user_id: Optional user ID for Mem0 memory retrieval.
        max_papers: Maximum papers to fetch.

    Returns:
        A fully initialized AgentState with all required fields set to defaults.
    """
    return AgentState(
        query=query,
        session_id=session_id,
        user_id=user_id,
        max_papers=max_papers,
        mem0_context="",
        papers=[],
        summaries=[],
        contradiction_report=None,
        concepts=[],
        final_synthesis="",
        evaluation=None,
        errors=[],
        qdrant_context=[],
    )
